<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ACCIFCConverter.Domain\ACCIFCConverter.Domain.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.5.2" />
  </ItemGroup>
</Project>